"""Redo migrate

Revision ID: 2839741eeec4
Revises: 
Create Date: 2024-08-29 15:59:26.300579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2839741eeec4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('djs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('produces', sa.Boolean(), nullable=False),
    sa.Column('dj_profile_picture', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'city', name='unique_dj_per_city')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('_hashed_password', sa.String(), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venuename', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dj_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dj_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dj_id'], ['djs.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dj_venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dj_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dj_id'], ['djs.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subgenres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_dj_favourites',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dj_id'], ['djs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('dj_subgenres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dj_id', sa.Integer(), nullable=True),
    sa.Column('subgenre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dj_id'], ['djs.id'], ),
    sa.ForeignKeyConstraint(['subgenre_id'], ['subgenres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dj_subgenres')
    op.drop_table('user_dj_favourites')
    op.drop_table('subgenres')
    op.drop_table('dj_venues')
    op.drop_table('dj_genres')
    op.drop_table('venues')
    op.drop_table('users')
    op.drop_table('genres')
    op.drop_table('djs')
    # ### end Alembic commands ###
