"""Add user-dj favourites relationship

Revision ID: 7a0ae1f62f6f
Revises: 142e9357c68d
Create Date: 2024-08-27 13:07:22.375937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0ae1f62f6f'
down_revision = '142e9357c68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_dj_favourites',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dj_id'], ['djs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_dj_favourites')
    # ### end Alembic commands ###
