"""Rename column asmin to is_admin in User model

Revision ID: ed677b7e1675
Revises: 738a06d957ae
Create Date: 2024-08-01 22:05:56.656009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed677b7e1675'
down_revision = '738a06d957ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_asmin', new_column_name='is_admin', existing_type=sa.Boolean(), existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin', new_column_name='is_asmin', existing_type=sa.Boolean(), existing_nullable=True)


    # ### end Alembic commands ###
